<?php

namespace Todo\Bundle\RestBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class RestController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Todo\Bundle\RestBundle\Controller\RestController();
        return $instance;
    }
}
